name: Docker Workflow

on:
  - push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: scriptsmithdev01
  IMAGE_NAME: e-com-app

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Publish
        run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  docker_deploy:
    needs: docker_build
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        env:
          DOCKER_PAT: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Docker Run
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest